#!/bin/bash

#   Copyright 2011 Shaunak Kashyap
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

source logging.sh

# Configurables
DAYTIME_SERVERS=( time-a.timefreq.bldrdoc.gov time-b.timefreq.bldrdoc.gov time-c.timefreq.bldrdoc.gov time-d.timefreq.bldrdoc.gov )
DAYTIME_MAX_ATTEMPTS=5
RETRY_INTERVAL=5

get_random_server() {

    rand_idx=$(expr $RANDOM % 4)
    echo ${DAYTIME_SERVERS[$rand_idx]}

}

get_daytime_line() {

    let num_attempts=1
    while [ $num_attempts -lt $DAYTIME_MAX_ATTEMPTS ]; do

    msg_prefix="[Attempt $num_attempts/$DAYTIME_MAX_ATTEMPTS]"

    chosen_server=$(get_random_server)
    LOG_DEBUG "$msg_prefix Attempting to get DAYTIME line from $chosen_server..."

    line=$(telnet $chosen_server 13 2>/dev/null | tail -1 | grep '^[0-9]')
    if [ "$line" != "" ]; then
        echo "$line"
	    return
	    fi
	    
	    let num_attempts=num_attempts+1
	    LOG_DEBUG "$msg_prefix Attempt failed. Sleeping for $RETRY_INTERVAL seconds before retrying..."
	    sleep $RETRY_INTERVAL
    done

    LOG_FATAL "Could not get DAYTIME line from servers in $DAYTIME_MAX_ATTEMPTS attempts. Giving up."
    exit 1
}

get_timestamp() {

    daytime_line=$(get_daytime_line)
    echo $daytime_line | awk '{printf "20%s%s%03d",$2,$3,$7}' | sed 's/[-:]//g'

}

LOG_LEVEL=$1
if [ "$LOG_LEVEL" == "" ]; then
    LOG_LEVEL=$LOG_LEVEL_INFO
fi

# Get user input
while [ "$DB_NAME" == "" ]; do
    read -ep "Database name: " DB_NAME
done

while [ "$BASEDIR" == "" ]; do
    read -ep "Migrations base directory: " BASEDIR
done

# Generate timestamp
timestamp=$(get_timestamp)

# Create directories
dir=$BASEDIR/$DB_NAME/$timestamp
file=$dir/up
mkdir -p $dir
touch $file

echo "Created $file" >&2
